import 'dart:developer';

const appName = "Sangrakshan";
const credits = "@Chakra-vyuha";
const appVersion = "Sangrakshan 1.0.0";
const username = "userName";
const namehint = "UserNameHINT";
const Password = "Password";
const PasswordHint = "PasswordHint";
const Login = "GET STARTED";
const home = "Home";
const Profile = "Profile";
const usern32ame = "username";
const score = "200";
const achievements = "12";
const metaverse = "Education Space";
const Chatbot = "BotHelp";
const ARService = "AR Drug Detection";
const Fdsaitness = "Fitness";
const Service = "Service";
const ConnectDapp = "Connect For HELP!";